# Use postgres/example user/password credentials
version: '3.9'

# To restart the database, use:
# docker-compose down --volumes
# docker compose up


services:

  db:
    container_name: db
    build: ./db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: db
      POSTGRES_PASSWORD: example
    user: postgres
#    expose:
#      - 5432
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  adminer:
    image: adminer
    restart: always
    ports:
      - "127.0.0.1:8079:8080"
  smtp:
    container_name: smtp
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      - "127.0.0.1:8069:80"
      - "127.0.0.1:2525:25"
  auth:
    container_name: auth
    build:
      context: ./
      dockerfile: auth-service/Dockerfile
    ports:
      - "127.0.0.1:8089:8089"
    depends_on:
      smtp:
        condition: service_started
      db:
        condition: service_healthy
  client:
    container_name: client
    build:
      context: ./
      dockerfile: client/Dockerfile
    ports:
      - "127.0.0.1:5100:5000"
    depends_on:
      db:
        condition: service_healthy
