# Use postgres/example user/password credentials
version: '3.3'

# To restart the database, use:
# docker-compose down --volumes
# docker compose up


services:

  db:
    build: ./db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: db
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
  adminer:
    image: adminer
    restart: always
    ports:
      - 8079:8079

