# Use postgres/example user/password credentials
version: '3.9'

# To restart the database, use:
# docker-compose down --volumes
# docker compose up


services:

  db:
    container_name: pussyhub_db
    build: ./db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: db
      POSTGRES_PASSWORD: example
    user: postgres
#    expose:
#      - 5432
    ports:
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  adminer:
    container_name: pussyhub_adminer
    image: adminer
    restart: always
    ports:
      - "8079:8080"
  smtp:
    container_name: pussyhub_smtp
    image: bytemark/smtp
    restart: always
  auth:
    container_name: pussyhub_auth
    build:
      context: ./
      dockerfile: auth-service/Dockerfile
    env_file:
      - ./.env
    ports:
      - "8089:8089"
    depends_on:
      smtp:
        condition: service_started
      db:
        condition: service_healthy
  stream:
    container_name: stream
    image: alqutami/rtmp-hls
    ports:
      - 1935:1935
      - 8080:8080
  api:
    container_name: pussyhub_api
    build:
      context: ./
      dockerfile: api-service/Dockerfile
    env_file:
      - ./.env
    ports:
      - "8001:8001"
    depends_on:
      db:
        condition: service_healthy
  client:
    container_name: pussyhub_client
    build:
      context: ./
      dockerfile: client/Dockerfile
    env_file:
      - ./.env
    ports:
      - "5100:5000"
    depends_on:
      db:
        condition: service_healthy
